create database customer_behavior;
use customer_behavior;
select * from customer ;



-- Q1. What is the total revenue generated by male vs. female customers?

select gender,Sum(purchase_amount) as revenue
from customer 
group by gender;

-- Q2. Which customers used a discount but still spent more that the average purchase amount?
select customer_id, purchase_amount
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating ?
select  item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from customer 
group by item_purchased
order by avg(review_rating) desc 
limit 5;

-- Q4.Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type,
round (avg(purchase_amount),2) 
from customer 
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do Subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribes

	SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM
    customer
GROUP BY subscription_status
ORDER BY total_revenue , avg_spend DESC;

-- Q6. Which 5  products have the hightest percentage of purchase with discounts applied?

select item_purchased, 
round(100 * sum(case when discount_applied = 'Yes' Then 1 Else 0 End)/count(*),2) as discount_rate 
from customer
group by item_purchased
order by discount_rate desc 
limit 5;


-- Q7. Segment Customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as ( 
select customer_id, previous_purchases, 
case 
when previous_purchases = 1 Then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment 
from customer 
) 
select customer_segment, count(*) as "Number of Customers"
from customer_type 
group by customer_segment ;


-- Q8. What are the top 3 most purchased products within each category ? 

with item_counts as ( 
select category, 
item_purchased, 
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank 
from customer 
group by category, item_purchased 
) 
select item_rank, category, item_purchased, total_orders
from item_counts 
where item_rank <=3;

-- Q9. Are Customers who are repeat buyers (more than 5 previous purchases) also likely to subscrible?
SELECT 
    subscription_status, COUNT(customer_id) AS repeat_buyers
FROM
    customer
WHERE
    previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group ? 
select age_group, 
sum(purchase_amount) as total_revenue 
from customer
group by age_group
order by total_revenue desc; 

